### ISSUE TITLE
After visiting the domain name, the site shown is Nginx's first try.

### ISSUE THREAD

**Issue by ricler** [johnrosen1/vpstoolbox#100] opened 2020-08-11 08:30 UTC
**Describe the bug**
After 51 days, visiting the domain now shows not the previously nice looking site, but the original interface of nginx.

when I try `apt update` in two vps, there some wrong message:
```
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:1 https://downloads.mariadb.com/MariaDB/mariadb-10.4/repo/debian buster InRelease
Ign:4 https://downloads.mariadb.com/MaxScale/2.4/debian buster InRelease
Hit:5 https://downloads.mariadb.com/Tools/debian buster InRelease
Hit:6 https://downloads.mariadb.com/MaxScale/2.4/debian buster Release
Ign:8 https://nginx.org/packages/mainline/debian buster InRelease
Err:9 http://security.debian.org/debian-security buster/updates InRelease
  Connection failed [IP:]
Err:10 https://nginx.org/packages/mainline/debian buster Release
  Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: ]
Reading package lists... Done
E: The repository 'https://nginx.org/packages/mainline/debian buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by johnrosen1** [comment] 2020-08-11 09:14
https://github.com/johnrosen1/vpstoolbox/commit/7a58d218cccc96d5365fc953a9333e21e96d41cc @ricler  it should be fixed,please try again,thanks!

**Comment by johnrosen1** [comment] 2020-08-11 09:20
https://github.com/johnrosen1/vpstoolbox/commit/67421d5a6fe23a1edfd702409725db1967abe5b2 maybe it is caused by system upgrade from debian 9 to 10 ,fixed now

**Comment by johnrosen1** [comment] 2020-08-12 10:37
closed

**Closed by johnrosen1** 2020-08-12 10:37 UTC
